// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZq-0gAhi-8HvX3TXv3k8KGB4OQJj_APo',
    appId: '1:487497986959:web:b0fe24e9713c7123cf51fa',
    messagingSenderId: '487497986959',
    projectId: 'rentme-548d8',
    authDomain: 'rentme-548d8.firebaseapp.com',
    storageBucket: 'rentme-548d8.firebasestorage.app',
    measurementId: 'G-CLGFJ4KKC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn0YF5JcdXeLd7d7i0_H1IOxH7UVdEzyc',
    appId: '1:487497986959:android:d20d06b554b1fefbcf51fa',
    messagingSenderId: '487497986959',
    projectId: 'rentme-548d8',
    storageBucket: 'rentme-548d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUQua5PVdLP_nJL7A2IAUvB4SJmxFqGbU',
    appId: '1:487497986959:ios:9765a4dd14396c62cf51fa',
    messagingSenderId: '487497986959',
    projectId: 'rentme-548d8',
    storageBucket: 'rentme-548d8.firebasestorage.app',
    iosBundleId: 'com.example.rentMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUQua5PVdLP_nJL7A2IAUvB4SJmxFqGbU',
    appId: '1:487497986959:ios:9765a4dd14396c62cf51fa',
    messagingSenderId: '487497986959',
    projectId: 'rentme-548d8',
    storageBucket: 'rentme-548d8.firebasestorage.app',
    iosBundleId: 'com.example.rentMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZq-0gAhi-8HvX3TXv3k8KGB4OQJj_APo',
    appId: '1:487497986959:web:9c1cbd05c331ab1ccf51fa',
    messagingSenderId: '487497986959',
    projectId: 'rentme-548d8',
    authDomain: 'rentme-548d8.firebaseapp.com',
    storageBucket: 'rentme-548d8.firebasestorage.app',
    measurementId: 'G-E9LVED70SE',
  );
}
